language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
before_install:
  - npm install mocha -g
  - mysql -e 'CREATE DATABASE zenndb_travis'
branches:
  only:
    - master
services: mysql
script:
  - npm run test-travis