language: node_js
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=travis
node_js:
  - 10
before_install:
  - npm install mocha -g
  - mysql -e 'CREATE DATABASE zenndb_travis'
  - mysql -e 'ALTER DATABASE zenndb_travis DEFAULT CHARACTER SET utf8'
branches:
  only:
    - master
services: mysql
script:
  - mocha --exit